apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_ofk_no
      fintlabs.no/org-id: ofk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ofk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/api/egrunnerverv/instances/930580694"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "ofk-no"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/beta/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/beta/actuator/health/liveness"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/actuator/prometheus"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/novari-flyt-egrunnerverv-gateway-out"
    target:
      kind: OnePasswordItem
      name: novari-flyt-egrunnerverv-dispatch-oauth2-client

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: OnePasswordItem
      name: fint-flyt-v1-slack-webhook
