spring:
  security:
    oauth2:
      client:
        provider:
          servicenow:
            token-uri: ${novari.flyt.egrunnerverv.dispatch.token-uri}
        registration:
          egrunnerverv:
            authorization-grant-type: password
            provider: servicenow
            client-id: ${novari.flyt.egrunnerverv.dispatch.client-id}
            client-secret: ${novari.flyt.egrunnerverv.dispatch.client-secret}
