fint:
  application-id: fint-flyt-egrunnerverv-gateway

novari:
  flyt:
    egrunnerverv:
      checkSaksansvarligEpost: true
      checkSaksbehandler: true
      checkEmailDomain: true
      dispatch:
        base-url: https://vigoikstest.service-now.com/api/now/table
        token-uri: https://vigoikstest.service-now.com/oauth_token.do
        tablenameSak: "x_nvas_grunnerverv_grunnerverv"
        tablenameJournalpost: "x_nvas_grunnerverv_dokumenter"
        instance-initial-delay: 120000
        instance-fixed-delay: 300000
        username:
        password:
        registrationId: egrunnerverv

logging:
  level:
    no.novari.cache.ehcache.FintEhCacheEventLogger: WARN

server:
  error:
    include-message: always
  max-http-request-header-size: 40KB

spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-postgres
      - flyt-resource-server
      - flyt-file-web-client
      - flyt-service-now-web-client

  http:
    codecs:
      max-in-memory-size: 100MB

  output:
    ansi:
      enabled: always
