fint:
  org-id: novari.no

novari:
  flyt:
    file-service-url: http://localhost:8091

    egrunnerverv:
      checkSaksansvarligEpost: false
      dispatch:
        base-url: https://vigoikstest.service-now.com/api/now/table
        token-uri: https://vigoikstest.service-now.com/oauth_token.do
        instance-dispatch-initial-delay: 20000
        instance-dispatch-fixed-delay: 10000

    instance-gateway:
      check-integration-exists: false

  kafka:
    default-replicas: 1
    topic:
      org-id: novari-no

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5441/fint-flyt-egrunnerverv-gateway
    username: postgres
    password: password
    hikari:
      schema: fintlabs_no

server:
  port: 8102

logging:
  level:
    no.novari.no.fintlabs.instance.EgrunnervervInstanceController: DEBUG

slack:
  webhook:
    url: ""
