spring:
  security:
    oauth2:
      client:
        provider:
          servicenow:
            token-uri: ${fint.flyt.egrunnerverv.dispatch.token-uri}
        registration:
          egrunnerverv:
            authorization-grant-type: password
            provider: servicenow
            client-id: ${fint.flyt.egrunnerverv.dispatch.client-id}
            client-secret: ${fint.flyt.egrunnerverv.dispatch.client-secret}
