apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemarkfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_telemarkfylke_no
      fintlabs.no/org-id: telemarkfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "telemarkfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "telemarkfylke.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/929882989"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "telemarkfylke-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksansvarligEpost
          value: "false"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksbehandler
          value: "false"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.base-url
          value: "https://vigoiks.service-now.com/api/now/table"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.token-uri
          value: "https://vigoiks.service-now.com/oauth_token.do"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway
