apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_bfk_no
      fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/930580260"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "bfk-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.base-url
          value: "https://vigoiks.service-now.com/api/now/table"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.token-uri
          value: "https://vigoiks.service-now.com/oauth_token.do"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway
