apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ffk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_ffk_no
      fintlabs.no/org-id: ffk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ffk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ffk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/api/egrunnerverv/instances/830090282"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "ffk-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksansvarligEpost
          value: "false"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksbehandler
          value: "false"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/actuator/health"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-gateway-out"
    target:
      kind: OnePasswordItem
      name: novari-flyt-egrunnerverv-dispatch-oauth2-client

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: OnePasswordItem
      name: fint-flyt-v1-slack-webhook
