apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_trondelagfylke_no
      fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/817920632"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "trondelagfylke-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksansvarligEpost
          value: "false"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.checkSaksbehandler
          value: "false"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.base-url
          value: "https://vigoiks.service-now.com/api/now/table"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.flyt.egrunnerverv.dispatch.token-uri
          value: "https://vigoiks.service-now.com/oauth_token.do"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/actuator/health/liveness"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway
